export interface Book {
  id: string;
  title: string;
  author: string;
  category: string;
  tagline: string;
  summary: string;
  keyLessons: string[];
  searchQuery: string;
  readerUrl: string;
  isFreeFull?: boolean; // true = full text available via readerUrl (Gutenberg etc.)
}

export const BOOKS: Book[] = [
  {
    id: 'atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    category: 'Systems',
    tagline: 'Tiny changes, remarkable results.',
    summary: 'Clear argues that improvement comes from 1% better every day, not dramatic leaps. The system matters more than the goal. He introduces the habit loop — cue, craving, response, reward — and shows how to engineer it deliberately. Identity-based habits ("I am someone who trains") stick longer than outcome-based ones ("I want to lose 10kg").',
    keyLessons: [
      'You do not rise to the level of your goals — you fall to the level of your systems.',
      'Make habits obvious, attractive, easy, and satisfying.',
      'Every action is a vote for the identity you want to become.',
      'Habit stacking: link new habits to existing ones.',
      '2-minute rule: scale any habit down to something you can do in 2 minutes first.',
    ],
    searchQuery: 'Atomic Habits James Clear free pdf',
    readerUrl: 'https://openlibrary.org/works/OL17930368W/Atomic_Habits',
  },
  {
    id: 'cant-hurt-me',
    title: "Can't Hurt Me",
    author: 'David Goggins',
    category: 'Discipline',
    tagline: 'Master your mind and defy the odds.',
    summary: 'Goggins grew up in poverty and abuse, became morbidly obese, then transformed into one of the world\'s toughest endurance athletes. The book is a raw account of what the human mind is capable of when comfort is eliminated. He introduces the 40% rule — when you think you\'re done, you\'re only at 40% of your actual capacity.',
    keyLessons: [
      'The 40% rule: your mind taps out long before your body does.',
      'The Accountability Mirror: confront your excuses daily.',
      'Callusing the mind: seek discomfort deliberately to build resilience.',
      'Taking souls: outwork people who doubt you, silently and consistently.',
      'The cookie jar: store your past wins mentally to draw on when you feel weak.',
    ],
    searchQuery: "Can't Hurt Me David Goggins free pdf",
    readerUrl: 'https://openlibrary.org/search?q=Can%27t+Hurt+Me+David+Goggins',
  },
  {
    id: 'meditations',
    title: 'Meditations',
    author: 'Marcus Aurelius',
    category: 'Stoicism',
    tagline: 'The private journal of a Roman emperor.',
    summary: 'Written by a man who ruled the most powerful empire on earth, Meditations was never meant to be published. It is Aurelius talking himself into living by his own values — reason, virtue, duty, and acceptance of what cannot be controlled. The stoic philosophy here is brutally practical: focus only on what is within your control and let everything else go.',
    keyLessons: [
      'You have power over your mind, not outside events.',
      'The obstacle is the way — difficulty is where character is forged.',
      'Do not waste time imagining the ideal life. Live the one you have.',
      'Your reputation belongs to others. Your character belongs to you.',
      'Each day, begin again. Yesterday\'s failures do not define today.',
    ],
    searchQuery: 'Meditations Marcus Aurelius free pdf Project Gutenberg',
    readerUrl: 'https://www.gutenberg.org/files/2680/2680-h/2680-h.htm',
    isFreeFull: true,
  },
  {
    id: 'deep-work',
    title: 'Deep Work',
    author: 'Cal Newport',
    category: 'Focus',
    tagline: 'Rules for focused success in a distracted world.',
    summary: 'Newport makes the case that the ability to focus without distraction is becoming both increasingly rare and increasingly valuable. He distinguishes deep work (cognitively demanding, focused) from shallow work (logistics, email, admin) and argues your career capital is determined by how much deep work you can produce. The book gives concrete scheduling strategies to protect focus time.',
    keyLessons: [
      'Shallow work is easy to do and easy to replace. Deep work is your edge.',
      'Schedule depth — don\'t hope for focus, block it in your calendar.',
      'Embrace boredom. Train your mind to resist distraction during idle moments.',
      'Quit social media unless it clearly advances your career goals.',
      'Shut down ritual: define when your workday ends and honour it completely.',
    ],
    searchQuery: 'Deep Work Cal Newport free pdf',
    readerUrl: 'https://openlibrary.org/search?q=Deep+Work+Cal+Newport',
  },
  {
    id: 'bhagavad-gita',
    title: 'The Bhagavad Gita',
    author: 'Vyasa (trans. various)',
    category: 'Spiritual',
    tagline: 'Do your duty. Detach from results.',
    summary: 'Set on a battlefield, the Gita is a dialogue between Prince Arjuna and Lord Krishna about duty, action, and the nature of existence. Its core teaching is nishkama karma — act fully and without attachment to the outcome. It covers three paths to liberation: action (karma yoga), knowledge (jnana yoga), and devotion (bhakti yoga). Highly practical for modern decision-making and inner peace.',
    keyLessons: [
      'You have a right to perform your duties, not to the fruits of your actions.',
      'The self is eternal — the body changes but consciousness continues.',
      'Equal-mindedness in success and failure is the mark of wisdom.',
      'Attachment to outcomes causes suffering. Engagement without attachment is freedom.',
      'Know your dharma (purpose) and pursue it with full commitment.',
    ],
    searchQuery: 'Bhagavad Gita free pdf English translation',
    readerUrl: 'https://www.gutenberg.org/files/2388/2388-h/2388-h.htm',
    isFreeFull: true,
  },
  {
    id: 'power-of-now',
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    category: 'Mental',
    tagline: 'Stop being a prisoner of your own mind.',
    summary: 'Tolle argues that most human suffering is created by the mind living in the past (guilt, regret) or the future (worry, anxiety). The present moment is the only place where life actually happens. The book teaches how to observe your thoughts without being consumed by them, creating what he calls the "witness consciousness." A bridge between Eastern meditation and Western psychology.',
    keyLessons: [
      'You are not your thoughts — you are the awareness behind them.',
      'The past is memory. The future is imagination. Only now is real.',
      'Pain bodies: accumulated emotional pain that hijacks your reactions.',
      'Presence is the antidote to compulsive thinking.',
      'Resistance to what is creates suffering. Acceptance creates peace.',
    ],
    searchQuery: 'The Power of Now Eckhart Tolle free pdf',
    readerUrl: 'https://openlibrary.org/search?q=The+Power+of+Now+Eckhart+Tolle',
  },
  {
    id: '48-laws',
    title: 'The 48 Laws of Power',
    author: 'Robert Greene',
    category: 'Strategy',
    tagline: 'Read this book. Then read it again.',
    summary: 'Greene distils 3,000 years of power dynamics into 48 laws, drawn from history, philosophy, and the lives of the most strategic figures who ever lived. The book is amoral — a manual for how power actually works, not how we wish it did. Essential for understanding social hierarchies, persuasion, and how to protect yourself from manipulation.',
    keyLessons: [
      'Never outshine the master — make superiors feel superior.',
      'Never put too much trust in allies. Learn to use enemies.',
      'Always say less than necessary — silence creates power.',
      'Reputation is your cornerstone. Guard it with your life.',
      'Court attention at all costs — obscurity is death.',
    ],
    searchQuery: 'The 48 Laws of Power Robert Greene free pdf',
    readerUrl: 'https://openlibrary.org/search?q=48+Laws+of+Power+Robert+Greene',
  },
  {
    id: 'mans-search',
    title: "Man's Search for Meaning",
    author: 'Viktor Frankl',
    category: 'Purpose',
    tagline: 'Everything can be taken except your response.',
    summary: 'A Holocaust survivor and psychiatrist describes life in Nazi concentration camps, using the extreme conditions to test his theory of logotherapy — that the primary human drive is not pleasure but meaning. The book shows that even in the worst conditions imaginable, people who had a "why" survived. It is one of the most important books written in the 20th century.',
    keyLessons: [
      'Those who have a WHY to live can bear almost any HOW.',
      'Between stimulus and response, there is a space. In that space is your freedom.',
      'Meaning can be found in work, love, and suffering.',
      'Suffering ceases to be suffering when it finds meaning.',
      'Don\'t aim at success — it will come as a side effect of dedication to a cause.',
    ],
    searchQuery: "Man's Search for Meaning Viktor Frankl free pdf",
    readerUrl: 'https://openlibrary.org/search?q=Man%27s+Search+for+Meaning+Viktor+Frankl',
  },
  {
    id: 'think-grow-rich',
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    category: 'Wealth',
    tagline: 'The principles behind every fortune.',
    summary: 'Hill spent 20 years interviewing 500 of the most successful people of his era — Ford, Carnegie, Edison, Roosevelt — and distilled 13 principles of success. The core idea is that a "burning desire" combined with a specific plan, auto-suggestion, and mastermind groups creates inevitable success. Written in 1937 but surprisingly relevant for mental programming and goal-setting.',
    keyLessons: [
      'Desire: the starting point of all achievement is a burning, obsessive want.',
      'Faith: visualise your goal as already achieved, then believe it fully.',
      'Specialized knowledge beats general knowledge every time.',
      'The mastermind principle: surround yourself with people who challenge you.',
      'Persistence is the sustained effort necessary to transform desire into reality.',
    ],
    searchQuery: 'Think and Grow Rich Napoleon Hill free pdf',
    readerUrl: 'https://www.gutenberg.org/files/1232/1232-h/1232-h.htm',
    isFreeFull: true,
  },
  {
    id: 'willpower',
    title: 'The War of Art',
    author: 'Steven Pressfield',
    category: 'Discipline',
    tagline: 'Break through the blocks and win your inner battles.',
    summary: 'Pressfield names the enemy clearly: Resistance. It is the internal force that stops you from doing your most important creative and self-improvement work. It shows up as procrastination, distraction, fear, and self-doubt. The book argues that the professional shows up every day regardless of mood or inspiration. Turning pro — committing fully — is the single most important decision.',
    keyLessons: [
      'Resistance is most powerful the closer you are to your real work.',
      'The amateur waits for inspiration. The professional works whether they feel like it or not.',
      'Fear is a compass — the most important thing you can do is what you fear most.',
      'Turning pro changes everything: your priorities, identity, and daily habits.',
      'Your creative enemy is always internal, never external.',
    ],
    searchQuery: 'The War of Art Steven Pressfield free pdf',
    readerUrl: 'https://openlibrary.org/search?q=The+War+of+Art+Steven+Pressfield',
  },
];
