export interface Citation {
  id: string;
  authors: string;
  year: number;
  title: string;
  journal?: string;
  doi?: string;
  url: string;
  topic: 'skincare' | 'fitness' | 'nutrition' | 'sleep' | 'mental' | 'facial';
  summary: string;
}

export const CITATIONS: Record<string, Citation> = {
  retinol_efficacy: {
    id: 'retinol_efficacy',
    authors: 'Mukherjee S, Date A, Patravale V, et al.',
    year: 2006,
    title: 'Retinoids in the treatment of skin aging: an overview of clinical efficacy and safety',
    journal: 'Clinical Interventions in Aging',
    doi: '10.2147/ciia.2006.1.4.327',
    url: 'https://doi.org/10.2147/ciia.2006.1.4.327',
    topic: 'skincare',
    summary: 'Topical retinoids are the most studied anti-aging actives and reduce fine lines, hyperpigmentation, and improve collagen.',
  },
  spf_aging: {
    id: 'spf_aging',
    authors: 'Hughes MCB, Williams GM, Baker P, Green AC',
    year: 2013,
    title: 'Sunscreen and prevention of skin aging: a randomized trial',
    journal: 'Annals of Internal Medicine',
    doi: '10.7326/0003-4819-158-11-201306040-00002',
    url: 'https://doi.org/10.7326/0003-4819-158-11-201306040-00002',
    topic: 'skincare',
    summary: 'Daily broad-spectrum sunscreen use significantly slowed skin aging compared to discretionary use over 4.5 years.',
  },
  niacinamide_barrier: {
    id: 'niacinamide_barrier',
    authors: 'Draelos ZD, Matsubara A, Smiles K',
    year: 2006,
    title: 'The effect of 2% niacinamide on facial sebum production',
    journal: 'Journal of Cosmetic and Laser Therapy',
    doi: '10.1080/14764170600717704',
    url: 'https://doi.org/10.1080/14764170600717704',
    topic: 'skincare',
    summary: '2% topical niacinamide reduces sebum excretion rate and casual sebum levels, useful in oily/acne-prone skin.',
  },
  bha_acne: {
    id: 'bha_acne',
    authors: 'Kessler E, Flanagan K, Chia C, Rogers C, Glaser D',
    year: 2008,
    title: 'Comparison of α- and β-hydroxy acid chemical peels in the treatment of mild to moderately severe facial acne',
    journal: 'Dermatologic Surgery',
    doi: '10.1111/j.1524-4725.2007.34014.x',
    url: 'https://doi.org/10.1111/j.1524-4725.2007.34014.x',
    topic: 'skincare',
    summary: 'Salicylic acid (BHA) is effective for comedonal and inflammatory acne, comparable to glycolic acid.',
  },
  ceramides_dry: {
    id: 'ceramides_dry',
    authors: 'Spada F, Barnes TM, Greive KA',
    year: 2018,
    title: 'Skin hydration is significantly increased by a cream formulated to mimic the skin\'s own natural moisturizing systems',
    journal: 'Clinical, Cosmetic and Investigational Dermatology',
    doi: '10.2147/CCID.S177697',
    url: 'https://doi.org/10.2147/CCID.S177697',
    topic: 'skincare',
    summary: 'Ceramide-based moisturizers significantly improve skin hydration and barrier function in dry skin.',
  },
  vitamin_c_antioxidant: {
    id: 'vitamin_c_antioxidant',
    authors: 'Pullar JM, Carr AC, Vissers MCM',
    year: 2017,
    title: 'The roles of vitamin C in skin health',
    journal: 'Nutrients',
    doi: '10.3390/nu9080866',
    url: 'https://doi.org/10.3390/nu9080866',
    topic: 'skincare',
    summary: 'Topical L-ascorbic acid neutralizes free radicals from UV exposure and supports collagen synthesis.',
  },

  hypertrophy_volume: {
    id: 'hypertrophy_volume',
    authors: 'Schoenfeld BJ, Ogborn D, Krieger JW',
    year: 2017,
    title: 'Dose-response relationship between weekly resistance training volume and increases in muscle mass',
    journal: 'Journal of Sports Sciences',
    doi: '10.1080/02640414.2016.1210197',
    url: 'https://doi.org/10.1080/02640414.2016.1210197',
    topic: 'fitness',
    summary: '10+ weekly sets per muscle group produce greater hypertrophy than lower volumes; diminishing returns above 20 sets.',
  },
  rep_range_hypertrophy: {
    id: 'rep_range_hypertrophy',
    authors: 'Schoenfeld BJ, Grgic J, Van Every DW, Plotkin DL',
    year: 2021,
    title: 'Loading recommendations for muscle strength, hypertrophy, and local endurance',
    journal: 'Sports',
    doi: '10.3390/sports9020032',
    url: 'https://doi.org/10.3390/sports9020032',
    topic: 'fitness',
    summary: 'Hypertrophy occurs across a wide rep range (5-30); proximity to failure matters more than specific load.',
  },
  warmup_efficacy: {
    id: 'warmup_efficacy',
    authors: 'McCrary JM, Ackermann BJ, Halaki M',
    year: 2015,
    title: 'A systematic review of the effects of upper body warm-up on performance and injury',
    journal: 'British Journal of Sports Medicine',
    doi: '10.1136/bjsports-2014-094228',
    url: 'https://doi.org/10.1136/bjsports-2014-094228',
    topic: 'fitness',
    summary: 'Targeted dynamic warmups improve performance and reduce injury risk in resistance training.',
  },
  static_stretching_recovery: {
    id: 'static_stretching_recovery',
    authors: 'Afonso J, Clemente FM, Nakamura FY, et al.',
    year: 2021,
    title: 'The effectiveness of post-exercise stretching in short-term and delayed recovery',
    journal: 'Frontiers in Physiology',
    doi: '10.3389/fphys.2021.677581',
    url: 'https://doi.org/10.3389/fphys.2021.677581',
    topic: 'fitness',
    summary: 'Post-exercise static stretching modestly improves perceived recovery and flexibility without harming next-session performance.',
  },
  protein_intake: {
    id: 'protein_intake',
    authors: 'Morton RW, Murphy KT, McKellar SR, et al.',
    year: 2018,
    title: 'A systematic review, meta-analysis and meta-regression of protein supplementation on resistance training',
    journal: 'British Journal of Sports Medicine',
    doi: '10.1136/bjsports-2017-097608',
    url: 'https://doi.org/10.1136/bjsports-2017-097608',
    topic: 'nutrition',
    summary: 'Protein intake of ~1.6 g/kg/day maximizes resistance-training-induced hypertrophy; little benefit beyond 2.2 g/kg/day.',
  },
  caloric_deficit: {
    id: 'caloric_deficit',
    authors: 'Hall KD, Kahan S',
    year: 2018,
    title: 'Maintenance of lost weight and long-term management of obesity',
    journal: 'Medical Clinics of North America',
    doi: '10.1016/j.mcna.2017.08.012',
    url: 'https://doi.org/10.1016/j.mcna.2017.08.012',
    topic: 'nutrition',
    summary: 'Sustained moderate caloric deficits with high protein preserve lean mass while reducing body fat.',
  },

  sleep_recovery: {
    id: 'sleep_recovery',
    authors: 'Walker MP',
    year: 2017,
    title: 'Why We Sleep: Unlocking the Power of Sleep and Dreams',
    journal: 'Scribner (review summarized)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/30311830/',
    topic: 'sleep',
    summary: 'Adults benefit from 7-9 hours of sleep; insufficient sleep impairs hormonal recovery, performance, and cognition.',
  },
  consistent_sleep_schedule: {
    id: 'consistent_sleep_schedule',
    authors: 'Chaput JP, Dutil C, Sampasa-Kanyinga H',
    year: 2018,
    title: 'Sleeping hours: what is the ideal number and how does age impact this?',
    journal: 'Nature and Science of Sleep',
    doi: '10.2147/NSS.S163071',
    url: 'https://doi.org/10.2147/NSS.S163071',
    topic: 'sleep',
    summary: 'Consistent bedtimes and wake-times improve sleep quality independently of total duration.',
  },

  meditation_anxiety: {
    id: 'meditation_anxiety',
    authors: 'Goyal M, Singh S, Sibinga EMS, et al.',
    year: 2014,
    title: 'Meditation programs for psychological stress and well-being: a systematic review and meta-analysis',
    journal: 'JAMA Internal Medicine',
    doi: '10.1001/jamainternmed.2013.13018',
    url: 'https://doi.org/10.1001/jamainternmed.2013.13018',
    topic: 'mental',
    summary: 'Mindfulness meditation programs show moderate evidence for reducing anxiety, depression, and pain.',
  },
  cold_exposure: {
    id: 'cold_exposure',
    authors: 'Esperland D, de Weerd L, Mercer JB',
    year: 2022,
    title: 'Health effects of voluntary exposure to cold water',
    journal: 'International Journal of Circumpolar Health',
    doi: '10.1080/22423982.2022.2111789',
    url: 'https://doi.org/10.1080/22423982.2022.2111789',
    topic: 'mental',
    summary: 'Voluntary cold exposure may improve mood, alertness, and brown-fat activity; evidence is preliminary.',
  },

  mewing_evidence: {
    id: 'mewing_evidence',
    authors: 'Lee UK, Graves LL, Friedlander AH',
    year: 2019,
    title: '"Mewing": Social media\'s alternative to orthognathic surgery?',
    journal: 'Journal of Oral and Maxillofacial Surgery',
    doi: '10.1016/j.joms.2019.04.030',
    url: 'https://doi.org/10.1016/j.joms.2019.04.030',
    topic: 'facial',
    summary: 'Tongue-posture techniques (mewing) lack robust evidence for adult skeletal change but may improve oral posture and breathing.',
  },
  myofunctional_therapy: {
    id: 'myofunctional_therapy',
    authors: 'Camacho M, Certal V, Abdullatif J, et al.',
    year: 2015,
    title: 'Myofunctional therapy to treat obstructive sleep apnea: a systematic review and meta-analysis',
    journal: 'Sleep',
    doi: '10.5665/sleep.4652',
    url: 'https://doi.org/10.5665/sleep.4652',
    topic: 'facial',
    summary: 'Orofacial muscle exercises reduce sleep apnea severity, supporting tongue, palate, and jaw conditioning value.',
  },

  step_count_mortality: {
    id: 'step_count_mortality',
    authors: 'Paluch AE, Bajpai S, Bassett DR, et al.',
    year: 2022,
    title: 'Daily steps and all-cause mortality: a meta-analysis of 15 international cohorts',
    journal: 'The Lancet Public Health',
    doi: '10.1016/S2468-2667(21)00302-9',
    url: 'https://doi.org/10.1016/S2468-2667(21)00302-9',
    topic: 'fitness',
    summary: 'Mortality decreases with higher step counts; benefits plateau around 6,000-8,000 steps for older adults and 8,000-10,000 for younger adults.',
  },
  hiit_efficacy: {
    id: 'hiit_efficacy',
    authors: 'Wewege M, van den Berg R, Ward RE, Keech A',
    year: 2017,
    title: 'The effects of high-intensity interval training vs moderate-intensity continuous training on body composition',
    journal: 'Obesity Reviews',
    doi: '10.1111/obr.12532',
    url: 'https://doi.org/10.1111/obr.12532',
    topic: 'fitness',
    summary: 'HIIT and moderate continuous training produce similar reductions in body fat for less time invested in HIIT.',
  },
  progressive_overload: {
    id: 'progressive_overload',
    authors: 'Plotkin D, Coleman M, Van Every D, et al.',
    year: 2022,
    title: 'Progressive overload without progressing load? The effects of load or repetition progression on muscular adaptations',
    journal: 'PeerJ',
    doi: '10.7717/peerj.14142',
    url: 'https://doi.org/10.7717/peerj.14142',
    topic: 'fitness',
    summary: 'Progressive overload can be achieved by adding reps or load; both drive hypertrophy when sets are taken close to failure.',
  },
  hydration_performance: {
    id: 'hydration_performance',
    authors: 'Sawka MN, Burke LM, Eichner ER, et al.',
    year: 2007,
    title: 'American College of Sports Medicine position stand: exercise and fluid replacement',
    journal: 'Medicine & Science in Sports & Exercise',
    doi: '10.1249/mss.0b013e31802ca597',
    url: 'https://doi.org/10.1249/mss.0b013e31802ca597',
    topic: 'fitness',
    summary: 'Dehydration of >2% body mass impairs aerobic performance and cognition; pre-hydrate and replace losses during exercise.',
  },
  caffeine_performance: {
    id: 'caffeine_performance',
    authors: 'Grgic J, Grgic I, Pickering C, et al.',
    year: 2020,
    title: 'Wake up and smell the coffee: caffeine supplementation and exercise performance',
    journal: 'British Journal of Sports Medicine',
    doi: '10.1136/bjsports-2018-100278',
    url: 'https://doi.org/10.1136/bjsports-2018-100278',
    topic: 'nutrition',
    summary: '3-6 mg/kg caffeine 30-60 min before exercise improves endurance, power, and strength outcomes.',
  },
  creatine_safety: {
    id: 'creatine_safety',
    authors: 'Kreider RB, Kalman DS, Antonio J, et al.',
    year: 2017,
    title: 'International Society of Sports Nutrition position stand: safety and efficacy of creatine supplementation',
    journal: 'Journal of the International Society of Sports Nutrition',
    doi: '10.1186/s12970-017-0173-z',
    url: 'https://doi.org/10.1186/s12970-017-0173-z',
    topic: 'nutrition',
    summary: 'Creatine monohydrate (3-5 g/day) is safe and effective for improving strength, power, and lean mass.',
  },
  blue_light_sleep: {
    id: 'blue_light_sleep',
    authors: 'Tähkämö L, Partonen T, Pesonen AK',
    year: 2019,
    title: 'Systematic review of light exposure impact on human circadian rhythm',
    journal: 'Chronobiology International',
    doi: '10.1080/07420528.2018.1527773',
    url: 'https://doi.org/10.1080/07420528.2018.1527773',
    topic: 'sleep',
    summary: 'Evening light, especially blue-spectrum, suppresses melatonin and delays sleep onset.',
  },
  morning_sunlight: {
    id: 'morning_sunlight',
    authors: 'Wams EJ, Woelders T, Marring I, et al.',
    year: 2017,
    title: 'Linking light exposure and subsequent sleep: a field polysomnography study in humans',
    journal: 'Sleep',
    doi: '10.1093/sleep/zsx165',
    url: 'https://doi.org/10.1093/sleep/zsx165',
    topic: 'sleep',
    summary: 'Morning bright-light exposure phase-advances circadian rhythm and improves sleep quality.',
  },
  fiber_satiety: {
    id: 'fiber_satiety',
    authors: 'Slavin J, Green H',
    year: 2007,
    title: 'Dietary fibre and satiety',
    journal: 'Nutrition Bulletin',
    doi: '10.1111/j.1467-3010.2007.00603.x',
    url: 'https://doi.org/10.1111/j.1467-3010.2007.00603.x',
    topic: 'nutrition',
    summary: 'High-fiber foods increase satiety and reduce energy intake at subsequent meals.',
  },
  reading_cognition: {
    id: 'reading_cognition',
    authors: 'Bavishi A, Slade MD, Levy BR',
    year: 2016,
    title: 'A chapter a day: association of book reading with longevity',
    journal: 'Social Science & Medicine',
    doi: '10.1016/j.socscimed.2016.07.014',
    url: 'https://doi.org/10.1016/j.socscimed.2016.07.014',
    topic: 'mental',
    summary: 'Regular book reading is associated with a survival advantage and improved cognitive engagement.',
  },
  gratitude_wellbeing: {
    id: 'gratitude_wellbeing',
    authors: 'Emmons RA, McCullough ME',
    year: 2003,
    title: 'Counting blessings versus burdens: an experimental investigation of gratitude and subjective well-being',
    journal: 'Journal of Personality and Social Psychology',
    doi: '10.1037/0022-3514.84.2.377',
    url: 'https://doi.org/10.1037/0022-3514.84.2.377',
    topic: 'mental',
    summary: 'Brief regular gratitude practice increases positive affect, life satisfaction, and prosocial behavior.',
  },
};

export function getCitation(id: string): Citation | null {
  return CITATIONS[id] ?? null;
}

export function citationsForTopic(topic: Citation['topic']): Citation[] {
  return Object.values(CITATIONS).filter((c) => c.topic === topic);
}

export function formatCitationShort(c: Citation): string {
  const firstAuthor = c.authors.split(',')[0];
  return `${firstAuthor} et al., ${c.year}`;
}
